const REGISTRATION_DATA_REQUEST = 'REGISTRATION_DATA_REQUEST';
const REGISTRATION_DATA_SUCCESS = 'REGISTRATION_DATA_SUCCESS';
const REGISTRATION_DATA_FAILURE = 'REGISTRATION_DATA_FAILURE';

export {
  REGISTRATION_DATA_REQUEST,
  REGISTRATION_DATA_SUCCESS,
  REGISTRATION_DATA_FAILURE,
};