export const REGISTRATION_DATA_REQUEST = 'REGISTRATION_DATA_REQUEST';
export const REGISTRATION_DATA_SUCCESS = 'REGISTRATION_DATA_SUCCESS';
export const REGISTRATION_DATA_FAILURE = 'REGISTRATION_DATA_FAILURE';
