export const HOME_COMPANIES_DATA_REQUEST = 'HOME_COMPANIES_DATA_REQUEST';
export const HOME_COMPANIES_DATA_SUCCESS = 'HOME_COMPANIES_DATA_SUCCESS';
export const HOME_COMPANIES_DATA_FAILURE = 'HOME_COMPANIES_DATA_FAILURE';

export const HOME_VACANCIES_DATA_REQUEST = 'HOME_VACANCIES_DATA_REQUEST';
export const HOME_VACANCIES_DATA_SUCCESS = 'HOME_VACANCIES_DATA_SUCCESS';
export const HOME_VACANCIES_DATA_FAILURE = 'HOME_VACANCIES_DATA_FAILURE';