export const COMPANIES_CREATE_REQUEST = 'COMPANIES_CREATE_REQUEST';
export const COMPANIES_CREATE_SUCCESS = 'COMPANIES_CREATE_SUCCESS';
export const COMPANIES_CREATE_FAILURE = 'COMPANIES_CREATE_FAILURE';
export const COMPANIES_CREATE_CLEAR = 'COMPANIES_CREATE_CLEAR';
