export const PROFILE_VACANCIES_REQUEST = 'PROFILE_VACANCIES_REQUEST';
export const PROFILE_VACANCIES_SUCCESS = 'PROFILE_VACANCIES_SUCCESS';
export const PROFILE_VACANCIES_FAILURE = 'PROFILE_VACANCIES_FAILURE';

export const PROFILE_COMPANIES_REQUEST = 'PROFILE_COMPANIES_REQUEST';
export const PROFILE_COMPANIES_SUCCESS = 'PROFILE_COMPANIES_SUCCESS';
export const PROFILE_COMPANIES_FAILURE = 'PROFILE_COMPANIES_FAILURE';
