export const VACANCIES_CREATE_REQUEST = 'VACANCIES_CREATE_REQUEST';
export const VACANCIES_CREATE_SUCCESS = 'VACANCIES_CREATE_SUCCESS';
export const VACANCIES_CREATE_FAILURE = 'VACANCIES_CREATE_FAILURE';
export const VACANCIES_CREATE_CLEAR = 'VACANCIES_CREATE_CLEAR';

export const VACANCIES_USER_COMPANIES_REQUEST = 'VACANCIES_USER_COMPANIES_REQUEST';
export const VACANCIES_USER_COMPANIES_SUCCESS = 'VACANCIES_USER_COMPANIES_SUCCESS';
export const VACANCIES_USER_COMPANIES_FAILURE = 'VACANCIES_USER_COMPANIES_FAILURE';

export const VACANCY_REQUEST = 'VACANCY_REQUEST';
export const VACANCY_SUCCESS = 'VACANCY_SUCCESS';
export const VACANCY_FAILURE = 'VACANCY_FAILURE';

export const VACANCY_FAVORITE_ADD_REQUEST = 'VACANCY_FAVORITE_ADD_REQUEST';
export const VACANCY_FAVORITE_ADD_SUCCESS = 'VACANCY_FAVORITE_ADD_SUCCESS';
export const VACANCY_FAVORITE_ADD_FAILURE = 'VACANCY_FAVORITE_ADD_FAILURE';
