const LOGIN_SIGN_IN_REQUEST = 'LOGIN_SIGN_IN_REQUEST';
const LOGIN_SIGN_IN_SUCCESS = 'LOGIN_SIGN_IN_SUCCESS';
const LOGIN_SIGN_IN_FAILURE = 'LOGIN_SIGN_IN_FAILURE';

const LOGIN_SIGN_OUT_REQUEST = 'LOGIN_SIGN_OUT_REQUEST';
const LOGIN_SIGN_OUT_SUCCESS = 'LOGIN_SIGN_OUT_SUCCESS';
const LOGIN_SIGN_OUT_FAILURE = 'LOGIN_SIGN_OUT_FAILURE';

export {
  LOGIN_SIGN_IN_REQUEST,
  LOGIN_SIGN_IN_SUCCESS,
  LOGIN_SIGN_IN_FAILURE,
  LOGIN_SIGN_OUT_REQUEST,
  LOGIN_SIGN_OUT_SUCCESS,
  LOGIN_SIGN_OUT_FAILURE,
};
