export const LOGIN_SIGN_IN_REQUEST = 'LOGIN_SIGN_IN_REQUEST';
export const LOGIN_SIGN_IN_SUCCESS = 'LOGIN_SIGN_IN_SUCCESS';
export const LOGIN_SIGN_IN_FAILURE = 'LOGIN_SIGN_IN_FAILURE';

export const LOGIN_SIGN_OUT_REQUEST = 'LOGIN_SIGN_OUT_REQUEST';
export const LOGIN_SIGN_OUT_SUCCESS = 'LOGIN_SIGN_OUT_SUCCESS';
export const LOGIN_SIGN_OUT_FAILURE = 'LOGIN_SIGN_OUT_FAILURE';
